name: Off-Chain CI
on:
  workflow_dispatch: #Can be triggered from the UI
  push:
    branches:
      - main
    paths:
      - 'src/offchain/**'
      - '.github/workflows/off-chain.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/offchain/**'
      - '.github/workflows/off-chain.yml'

jobs:
  build-offchain:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '17.x']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies (CI)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
